# Site settings
title: "RasaDM News Hub"
description: "Latest insights, trends, and breakthroughs in AI-powered content automation and marketing technology"
baseurl: ""
url: "https://rasadm.github.io/latest"
author: "RasaDM Team"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# SEO
twitter:
  username: rasadm
  card: summary_large_image

facebook:
  app_id: 
  publisher: 

social:
  name: RasaDM
  links:
    - https://github.com/rasadm

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "RasaDM Team"
      show_excerpts: true 