# Site settings
title: "RasaDM News Hub"
description: "Latest insights, trends, and breakthroughs in AI-powered content automation and marketing technology"
baseurl: ""
url: "https://rasadm.github.io/latest"
author: "RasaDM Team"
email: "news@rasadm.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Theme - Using minimal-mistakes for better design
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Site Author
author:
  name: "RasaDM Team"
  avatar: "/assets/images/rasadm-logo.png"
  bio: "AI-powered content automation experts delivering strategic intelligence for marketing professionals."
  email: "news@rasadm.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rasadm"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rasadm.com"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rasadm"

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - package.json
  - Rakefile
  - tmp

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 6
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      sidebar:
        nav: "main"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

# Analytics
analytics:
  provider: false

# Social Sharing
social:
  type: Organization
  name: RasaDM
  links:
    - "https://github.com/rasadm"

# SEO
twitter:
  username: rasadm
  card: summary_large_image

og_image: "/assets/images/rasadm-social.png"

# Site Navigation
main:
  - title: "Home"
    url: /
  - title: "News"
    url: /news/
  - title: "Analysis"
    url: /analysis/
  - title: "About"
    url: /about/
  - title: "Archive"
    url: /archive/ 