# Site settings
title: "RasaDM News Hub"
description: "Latest insights, trends, and breakthroughs in AI-powered content automation and marketing technology"
baseurl: ""
url: "https://rasadm.github.io/latest"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Use a simple, reliable theme
theme: minima

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site Author
author:
  name: "RasaDM Team"
  email: "news@rasadm.com"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# Collections
collections:
  posts:
    output: true

# SEO
twitter:
  username: rasadm

# Header pages
header_pages:
  - _pages/about.md
  - _pages/news.md
  - _pages/analysis.md
  - _pages/archive.md 